# PyTorch

In [5]:
import torch

display(torch.cuda.is_available())
display(torch.rand(2, 2))

True

tensor([[0.9259, 0.6924],
        [0.2411, 0.0517]])

## Создание тензоров

In [7]:
# создание тензора
x = torch.tensor([[5, 0, 1], [4, 8, 1], [0, 0, 1]])
display(x)

tensor([[5, 0, 1],
        [4, 8, 1],
        [0, 0, 1]])

In [8]:
# Изменение элемента тензора
x[0][0] = 42
display(x)

tensor([[42,  0,  1],
        [ 4,  8,  1],
        [ 0,  0,  1]])

In [10]:
# Создание нулевых и единичных тензоров

x0 = torch.zeros(3, 3)
display(x0)

x1 = torch.ones(3, 3)
display(x1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [51]:
# Извлечение данных из тензора нулевого ранга
torch.rand(1).item()

0.4288950562477112

## Операции над тензорами

In [69]:
# Максимальные, минимальные элементы и сумма элементов
display(torch.rand(8, 8).max())
display(torch.rand(8, 8).min())
display(torch.rand(8, 8).sum())

tensor(0.9864)

tensor(0.0285)

tensor(32.9515)